### ISSUE TITLE
can't connect a miner to the wallet

### ISSUE THREAD

**Issue by djm34** [MiniblockchainProject/Cryptonite#1]
When I try to mine from outside the wallet, I get and error message: JSON invalid data

**Comment by MiniblockchainProject** [comment]
What exactly are you sending it? You have managed to deal with the strange getwork? The output is just hexification of the raw block structure. You'll also notice that the target hash is little endian. Our CBlockHeader is very strange having length modulo 4 == 2 and the nonce is not the last element of the struct. None of the getwork is tested to work. Sort of have plans to implement getblocktemplate.

**Comment by djm34** [comment]
I am not entirely sure... (I don't know much about those protocol). 
Can you point me to file containing the CBlockHeader in the source.

**Comment by MiniblockchainProject** [comment]
core.h line 304

**Comment by MiniblockchainProject** [comment]
I wrote a reference cpu miner. Some changes were made to the wallet, so you'll need that first. 
https://github.com/MiniblockchainProject/Minerd
